# This is the config file for travis-ci for PINT

language: python

matrix:
    fast_finish: true
    include:
        - script: wget https://data.nanograv.org/static/data/ephem/de405.bsp
          name: "NANOGrav ephemeris server accessible"
          install: []
          services: []
          after_success: []
          git:
              clone: false
        - script: flake8-diff
          install: 
            - pip install -r requirements_dev.txt
            - pip install -r requirements.txt
            - pip install .
          name: "python style checker for changed code"
          services: []
          after_success: []
          before_script: git fetch --unshallow
        - python: "2.7"
        - python: "3.5"
        - python: "3.6"
        - python: "3.7"
        - name: "tox"
          sudo: false
          language: python
          python: 
            - "3.7"
            - "2.7"
          install: pip install tox-travis
          script: tox
        - script: make notebooks
          name: "Example notebooks (python 3.7)"
          python: "3.7"
        - script: make docs-build
          install: 
            - pip install -r requirements_dev.txt
            - pip install -r requirements.txt
            - pip install .
          name: "Documentation build"
          python: "3.7"
          after_success: []
    allow_failures:
        - script: flake8-diff
sudo: required

# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
#before_script:
#    - "export DISPLAY=:99.0"
#    - "sh -e /etc/init.d/xvfb start"
#    - sleep 3 # give xvfb some time to start

services:
    - xvfb

before_install:
    - sudo apt-get install pandoc

install:
    # We need to require the dev requirements first in case they're more
    # stringent (on version numbers)
    - pip install -r requirements_dev.txt
    - pip install -r requirements.txt
    - pip install .
    - python -c "from astropy.utils.data import download_file; from astropy.utils.iers import IERS_A_URL; download_file(IERS_A_URL, cache=True)"

#script:
#    - pwd
#    - make test

script:
    - ( cd tests && pytest --cov=pint )

after_success:
    ( cd tests && coveralls )

cache:
  directories:
    - $HOME/.astropy/cache
